version: '3.7'
services:
  tomcat-soap:
    container_name: tomcat-soap
    build:
      context: .
      dockerfile: Dockerfile.soap.tomcat9
    ports:
     - "8181:8080"
    links: 
     - "postgres-soap:dbserver"
     - "webserver:restserver"
  postgres-soap:
    container_name: postgres-soap
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    build:
      context: .
      dockerfile: Dockerfile.soap.postgres
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data:rw

  webserver:
    build:
      context: .
      dockerfile: ./Dockerfilephpwebserver
    ports:
     - "8080:80"
    volumes:
      - ./TrainFilteringWS:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest
    volumes:
      - ./TrainFilteringWS/sql:/docker-entrypoint-initdb.d

volumes:
  postgres_data: {}