version: '3.7'
services:
  java-client:
    container_name: java-client
    build:
      context: .
      dockerfile: Dockerfile.client.java-mvn
    working_dir: /home/root
    links:
     - "tomcat-soap:soap-ws"
  tomcat-soap:
    container_name: tomcat-soap
    build:
      context: .
      dockerfile: Dockerfile.soap.tomcat9
    ports:
     - "8181:8080"
    links: 
     - "postgres-soap:dbserver"
  postgres-soap:
    container_name: postgres-soap
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    build:
      context: .
      dockerfile: Dockerfile.soap.postgres
    # ports: 
    #   - "5433:5432"
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data: {}