version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: ./Dockerfilephpwebserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./TrainFilteringWS:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest
    volumes:
      - ./TrainFilteringWS/sql:/docker-entrypoint-initdb.d
    #   - ./TrainFilteringWS/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - mysql